export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';

export const SET_USERNAME = 'SET_USERNAME';
export const SET_CHOOSE_NAME = 'SET_CHOOSE_NAME';

export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';

export const START_NEXT_VIDEO = 'START_NEXT_VIDEO';
export const SET_ALLOW_SEEK = 'SET_ALLOW_SEEK';
export const SET_WAIT_LIST = 'SET_WAIT_LIST';

export const SET_SEARCH_VIDEOS = 'SET_SEARCH_VIDEOS';

export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const REMOVE_FROM_PLAYLIST = 'REMOVE_FROM_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const SET_PLAYLISTS = 'SET_PLAYLISTS';
