export const BEFORE_CHOOSE_NAME = 'BEFORE_CHOOSE_NAME';
export const DURING_CHOOSE_NAME = 'DURING_CHOOSE_NAME';
export const DURING_CHOOSE_AUTH_NAME = 'DURING_CHOOSE_AUTH_NAME';
export const AFTER_CHOOSE_AUTH_NAME = 'AFTER_CHOOSE_AUTH_NAME';
export const AFTER_CHOOSE_NAME = 'AFTER_CHOOSE_NAME';
